<table class='change-spec info-content'>
    <tr>
        <td>
            <p>Publisher</p>
        </td>
        <td>
            <p>:</p>
        </td>
        <td>
            <p>Universitas Brawijaya</p>
        </td>
    </tr>
    <tr>
        <td>
            <p>Category</p>
        </td>
        <td>
            <p>:</p>
        </td>
        <td>
            <p>Pendidikan</p>
        </td>
    </tr>
    <tr>
        <td>
            <p>Pages</p>
        </td>
        <td>
            <p>:</p>
        </td>
        <td>
            <p>485</p>
        </td>
    </tr>
    <tr>
        <td>
            <p>ISBN</p>
        </td>
        <td>
            <p>:</p>
        </td>
        <td>
            <p>978-602-397-482-5</p>
        </td>
    </tr>
    <tr>
        <td>
            <p>Size</p>
        </td>
        <td>
            <p>:</p>
        </td>
        <td>
            <p>16cm X 25cm</p>
            <p>HVS 70 gsm</p>
        </td>
    </tr>
    <tr>
        <td>
            <p>Harga</p>
        </td>
        <td>
            <p>:</p>
        </td>
        <td>
            <p>Rp. 150.000,00</p>
        </td>
    </tr>
</table>