<table class='change-spec info-content'>
    <tr>
        <td>
            <p>Publisher</p>
        </td>
        <td>
            <p>:</p>
        </td>
        <td>
            <p>Universitas Brawijaya</p>
        </td>
    </tr>
    <tr>
        <td>
            <p>Category</p>
        </td>
        <td>
            <p>:</p>
        </td>
        <td>
            <p>Pendidikan</p>
        </td>
    </tr>
    <tr>
        <td>
            <p>Pages</p>
        </td>
        <td>
            <p>:</p>
        </td>
        <td>
            <p>485</p>
        </td>
    </tr>
    <tr>
        <td>
            <p>ISBN</p>
        </td>
        <td>
            <p>:</p>
        </td>
        <td>
            <p>978-652-789-650-2</p>
        </td>
    </tr>
    <tr>
        <td>
            <p>Size</p>
        </td>
        <td>
            <p>:</p>
        </td>
        <td>
            <p>16cm X 25cm</p>
            <p>PDF</p>
        </td>
    </tr>
    <tr>
        <td>
            <p>Harga</p>
        </td>
        <td>
            <p>:</p>
        </td>
        <td>
            <p>Rp. <?php echo $book['price_books'] ?></p>
        </td>
    </tr>
</table>